auto: true
server: true
markdown: rdiscount
pygments: true
exclude: ['README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js', '*.bat']
permalink: /:year/:month/:title
paginate: 9
encoding: "UTF-8"